name: CI
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: install luna client
        run: |
          curl -O https://oesterild.dk/luna-min10.6.tar
          sudo tar -C /usr/local -xf luna-min10.6.tar
          sudo chown -R root.root /usr/local/luna
          find /usr/local/luna -ls

      - name: Install files
        env:
          CAFILE: ${{ secrets.CAFILE }}
          CLIENTCERT: ${{ secrets.CLIENTCERT }}
          CLIENTKEY: ${{ secrets.CLIENTKEY }}
          CHRYSTOKI: ${{ secrets.CHRYSTOKI }}
        run: |
          sudo echo ${CAFILE} >/usr/local/luna/cert/server/CAFile.pem
          sudo echo ${CLIENTCERT} >/usr/local/luna/cert/client/172.30.0.20.pem
          sudo echo ${CLIENTKEY} >/usr/local/luna/cert/client/172.30.0.20Key.pem
          sudo echo ${CHRYSTOKI} >/usr/local/luna/Chrystoki.conf

      - name: Test stuf 3
        run: echo "${{vars.CHRYSTOKICONFIGURATIONPATH}}"

