name: CI
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: install luna client
        run: |
          curl -O https://oesterild.dk/luna-min10.6.tar
          curl -O https://oesterild.dk/lunacm
          sudo tar -C /usr/local -xf luna-min10.6.tar
          sudo mkdir /usr/local/luna/bin
          sudo mv lunacm /usr/local/luna/bin
          sudo chmod +x /usr/local/luna/bin/lunacm
          sudo groupadd -r -g 991 hsmusers
          sudo usermod -aG hsmusers runner

      - name: Install files
        env:
          CAFILE: ${{ secrets.CAFILE }}
          CLIENTCERT: ${{ secrets.CLIENTCERT }}
          CLIENTKEY: ${{ secrets.CLIENTKEY }}
          CHRYSTOKI: ${{ secrets.CHRYSTOKI }}
        run: |
          sudo bash -c "echo '${CAFILE}' >/usr/local/luna/cert/server/CAFile.pem"
          sudo bash -c "echo '${CLIENTCERT}' >/usr/local/luna/cert/client/172.30.0.20.pem"
          sudo bash -c "echo '${CLIENTKEY}' >/usr/local/luna/cert/client/172.30.0.20Key.pem"
          sudo bash -c "echo '${CHRYSTOKI}' >/usr/local/luna/Chrystoki.conf"
          sudo chown -R runner /usr/local/luna
          find /usr/local/luna -ls 

      - name: Test stuf 3
        env:
          CHRYSTOKICONFIGURATIONPATH: ${{vars.CHRYSTOKICONFIGURATIONPATH}}
        run: |
          echo ${ChrystokiConfigurationPath}
          /usr/local/luna/bin/lunacm -q slot list

