name: CI
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test stuf 2
        env:
          CAFILE: ${{ secrets.CAFILE }}
        run: |
          echo ${CAFILE} >cafile.pem
          ls -l

      - name: Test stuf 3
        run: env|grep -i chrys

