name: CI
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        go_version: ["1.21"]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test stuff
        run: pwd

      - name: Test stuf 2
        run: env

      - name: Test stuf 3
        run: go env
