name: CI
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: install luna client
        run: |
          curl -O https://oesterild.dk/luna-min10.6.tar
          sudo tar -C /usr/local -xf luna-min10.6.tar

      - name: Test stuf 2
        env:
          CAFILE: ${{ secrets.CAFILE }}
        run: |
          echo ${CAFILE} >/usr/local/luna/cert/server/CAFile.pem
          find /usr/local/luna

      - name: Test stuf 3
        run: echo "${{vars.CHRYSTOKICONFIGURATIONPATH}}"

